[tool.poetry]
name = "fastapi-backend-api-integration"
version = "0.1.0"
description = "FastAPI Backend API Integration Learning Journey"
authors = [
    "Zarmeen Rasool"
]
readme = "README.md"

packages = [
    { include = "todos" }
]

[tool.poetry.dependencies]
python = ">=3.14"

fastapi = ">=0.141.1,<0.142.0"
sql = ">=2022.4.0,<2023.0.0"
sqlmodel = ">=0.0.39,<0.0.40"
uvicorn = { version = ">=0.52.1,<0.53.0", extras = ["standard"] }
sqlalchemy = ">=2.0.51,<3.0.0"
pydantic = ">=2.13.4,<3.0.0"
python-dotenv = ">=1.2.2,<2.0.0"
psycopg2-binary = ">=2.9.12,<3.0.0"
mypy = "^2.3.0"

[tool.poetry.scripts]
dev = "todos.SendResponse:start"
execute = "todos.sendrequest:running"
start = "todos.pythontypesPydanticAnnotated:type"
ven = "todos.QueryPathParameters:type"
func = "todos.FastApiBodyParameters:type"
exe = "todos.QueryParametersStringNumValidations:type"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"